/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sync/sync.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sync/sync.pb-c.h"
void   sync__file_info__init
                     (Sync__FileInfo         *message)
{
  static const Sync__FileInfo init_value = SYNC__FILE_INFO__INIT;
  *message = init_value;
}
size_t sync__file_info__get_packed_size
                     (const Sync__FileInfo *message)
{
  assert(message->base.descriptor == &sync__file_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sync__file_info__pack
                     (const Sync__FileInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sync__file_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sync__file_info__pack_to_buffer
                     (const Sync__FileInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sync__file_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sync__FileInfo *
       sync__file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sync__FileInfo *)
     protobuf_c_message_unpack (&sync__file_info__descriptor,
                                allocator, len, data);
}
void   sync__file_info__free_unpacked
                     (Sync__FileInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sync__file_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sync__get_sync_response__init
                     (Sync__GetSyncResponse         *message)
{
  static const Sync__GetSyncResponse init_value = SYNC__GET_SYNC_RESPONSE__INIT;
  *message = init_value;
}
size_t sync__get_sync_response__get_packed_size
                     (const Sync__GetSyncResponse *message)
{
  assert(message->base.descriptor == &sync__get_sync_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sync__get_sync_response__pack
                     (const Sync__GetSyncResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sync__get_sync_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sync__get_sync_response__pack_to_buffer
                     (const Sync__GetSyncResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sync__get_sync_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sync__GetSyncResponse *
       sync__get_sync_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sync__GetSyncResponse *)
     protobuf_c_message_unpack (&sync__get_sync_response__descriptor,
                                allocator, len, data);
}
void   sync__get_sync_response__free_unpacked
                     (Sync__GetSyncResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sync__get_sync_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sync__file_info__field_descriptors[2] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sync__FileInfo, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sync__FileInfo, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sync__file_info__field_indices_by_name[] = {
  1,   /* field[1] = filename */
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange sync__file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sync__file_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sync.FileInfo",
  "FileInfo",
  "Sync__FileInfo",
  "sync",
  sizeof(Sync__FileInfo),
  2,
  sync__file_info__field_descriptors,
  sync__file_info__field_indices_by_name,
  1,  sync__file_info__number_ranges,
  (ProtobufCMessageInit) sync__file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sync__get_sync_response__field_descriptors[1] =
{
  {
    "files",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Sync__GetSyncResponse, n_files),
    offsetof(Sync__GetSyncResponse, files),
    &sync__file_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sync__get_sync_response__field_indices_by_name[] = {
  0,   /* field[0] = files */
};
static const ProtobufCIntRange sync__get_sync_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sync__get_sync_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sync.GetSyncResponse",
  "GetSyncResponse",
  "Sync__GetSyncResponse",
  "sync",
  sizeof(Sync__GetSyncResponse),
  1,
  sync__get_sync_response__field_descriptors,
  sync__get_sync_response__field_indices_by_name,
  1,  sync__get_sync_response__number_ranges,
  (ProtobufCMessageInit) sync__get_sync_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor sync__sync_service__method_descriptors[1] =
{
  { "GetSync", &google__protobuf__empty__descriptor, &sync__get_sync_response__descriptor },
};
const unsigned sync__sync_service__method_indices_by_name[] = {
  0         /* GetSync */
};
const ProtobufCServiceDescriptor sync__sync_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "sync.SyncService",
  "SyncService",
  "Sync__SyncService",
  "sync",
  1,
  sync__sync_service__method_descriptors,
  sync__sync_service__method_indices_by_name
};
void sync__sync_service__get_sync(ProtobufCService *service,
                                  const Google__Protobuf__Empty *input,
                                  Sync__GetSyncResponse_Closure closure,
                                  void *closure_data)
{
  assert(service->descriptor == &sync__sync_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void sync__sync_service__init (Sync__SyncService_Service *service,
                               Sync__SyncService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &sync__sync_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
