/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sync/sync.proto */

#ifndef PROTOBUF_C_sync_2fsync_2eproto__INCLUDED
#define PROTOBUF_C_sync_2fsync_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "google/protobuf/empty.pb-c.h"

typedef struct Sync__FileInfo Sync__FileInfo;
typedef struct Sync__GetSyncResponse Sync__GetSyncResponse;


/* --- enums --- */


/* --- messages --- */

struct  Sync__FileInfo
{
  ProtobufCMessage base;
  char *hash;
  char *filename;
};
#define SYNC__FILE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sync__file_info__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Sync__GetSyncResponse
{
  ProtobufCMessage base;
  size_t n_files;
  Sync__FileInfo **files;
};
#define SYNC__GET_SYNC_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sync__get_sync_response__descriptor) \
    , 0,NULL }


/* Sync__FileInfo methods */
void   sync__file_info__init
                     (Sync__FileInfo         *message);
size_t sync__file_info__get_packed_size
                     (const Sync__FileInfo   *message);
size_t sync__file_info__pack
                     (const Sync__FileInfo   *message,
                      uint8_t             *out);
size_t sync__file_info__pack_to_buffer
                     (const Sync__FileInfo   *message,
                      ProtobufCBuffer     *buffer);
Sync__FileInfo *
       sync__file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sync__file_info__free_unpacked
                     (Sync__FileInfo *message,
                      ProtobufCAllocator *allocator);
/* Sync__GetSyncResponse methods */
void   sync__get_sync_response__init
                     (Sync__GetSyncResponse         *message);
size_t sync__get_sync_response__get_packed_size
                     (const Sync__GetSyncResponse   *message);
size_t sync__get_sync_response__pack
                     (const Sync__GetSyncResponse   *message,
                      uint8_t             *out);
size_t sync__get_sync_response__pack_to_buffer
                     (const Sync__GetSyncResponse   *message,
                      ProtobufCBuffer     *buffer);
Sync__GetSyncResponse *
       sync__get_sync_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sync__get_sync_response__free_unpacked
                     (Sync__GetSyncResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Sync__FileInfo_Closure)
                 (const Sync__FileInfo *message,
                  void *closure_data);
typedef void (*Sync__GetSyncResponse_Closure)
                 (const Sync__GetSyncResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct Sync__SyncService_Service Sync__SyncService_Service;
struct Sync__SyncService_Service
{
  ProtobufCService base;
  void (*get_sync)(Sync__SyncService_Service *service,
                   const Google__Protobuf__Empty *input,
                   Sync__GetSyncResponse_Closure closure,
                   void *closure_data);
};
typedef void (*Sync__SyncService_ServiceDestroy)(Sync__SyncService_Service *);
void sync__sync_service__init (Sync__SyncService_Service *service,
                               Sync__SyncService_ServiceDestroy destroy);
#define SYNC__SYNC_SERVICE__BASE_INIT \
    { &sync__sync_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define SYNC__SYNC_SERVICE__INIT(function_prefix__) \
    { SYNC__SYNC_SERVICE__BASE_INIT,\
      function_prefix__ ## get_sync  }
void sync__sync_service__get_sync(ProtobufCService *service,
                                  const Google__Protobuf__Empty *input,
                                  Sync__GetSyncResponse_Closure closure,
                                  void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sync__file_info__descriptor;
extern const ProtobufCMessageDescriptor sync__get_sync_response__descriptor;
extern const ProtobufCServiceDescriptor sync__sync_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sync_2fsync_2eproto__INCLUDED */
