/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: file/file.proto */

#ifndef PROTOBUF_C_file_2ffile_2eproto__INCLUDED
#define PROTOBUF_C_file_2ffile_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct File__UploadRequest File__UploadRequest;
typedef struct File__FileMetadata File__FileMetadata;
typedef struct File__UploadResponse File__UploadResponse;
typedef struct File__DownloadRequest File__DownloadRequest;
typedef struct File__DownloadResponse File__DownloadResponse;
typedef struct File__DeleteRequest File__DeleteRequest;
typedef struct File__DeleteResponse File__DeleteResponse;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  FILE__UPLOAD_REQUEST__DATA__NOT_SET = 0,
  FILE__UPLOAD_REQUEST__DATA_METADATA = 1,
  FILE__UPLOAD_REQUEST__DATA_CHUNK = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FILE__UPLOAD_REQUEST__DATA__CASE)
} File__UploadRequest__DataCase;

struct  File__UploadRequest
{
  ProtobufCMessage base;
  File__UploadRequest__DataCase data_case;
  union {
    ProtobufCBinaryData chunk;
    File__FileMetadata *metadata;
  };
};
#define FILE__UPLOAD_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__upload_request__descriptor) \
    , FILE__UPLOAD_REQUEST__DATA__NOT_SET, { {0} } }


struct  File__FileMetadata
{
  ProtobufCMessage base;
  char *filename;
  char *title;
  char *artist;
  char *album;
  int32_t duration;
};
#define FILE__FILE_METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__file_metadata__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  File__UploadResponse
{
  ProtobufCMessage base;
  char *hash;
};
#define FILE__UPLOAD_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__upload_response__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  File__DownloadRequest
{
  ProtobufCMessage base;
  char *hash;
};
#define FILE__DOWNLOAD_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__download_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  File__DownloadResponse
{
  ProtobufCMessage base;
  ProtobufCBinaryData chunk;
};
#define FILE__DOWNLOAD_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__download_response__descriptor) \
    , {0,NULL} }


struct  File__DeleteRequest
{
  ProtobufCMessage base;
  char *hash;
};
#define FILE__DELETE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__delete_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  File__DeleteResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
};
#define FILE__DELETE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__delete_response__descriptor) \
    , 0 }


/* File__UploadRequest methods */
void   file__upload_request__init
                     (File__UploadRequest         *message);
size_t file__upload_request__get_packed_size
                     (const File__UploadRequest   *message);
size_t file__upload_request__pack
                     (const File__UploadRequest   *message,
                      uint8_t             *out);
size_t file__upload_request__pack_to_buffer
                     (const File__UploadRequest   *message,
                      ProtobufCBuffer     *buffer);
File__UploadRequest *
       file__upload_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__upload_request__free_unpacked
                     (File__UploadRequest *message,
                      ProtobufCAllocator *allocator);
/* File__FileMetadata methods */
void   file__file_metadata__init
                     (File__FileMetadata         *message);
size_t file__file_metadata__get_packed_size
                     (const File__FileMetadata   *message);
size_t file__file_metadata__pack
                     (const File__FileMetadata   *message,
                      uint8_t             *out);
size_t file__file_metadata__pack_to_buffer
                     (const File__FileMetadata   *message,
                      ProtobufCBuffer     *buffer);
File__FileMetadata *
       file__file_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__file_metadata__free_unpacked
                     (File__FileMetadata *message,
                      ProtobufCAllocator *allocator);
/* File__UploadResponse methods */
void   file__upload_response__init
                     (File__UploadResponse         *message);
size_t file__upload_response__get_packed_size
                     (const File__UploadResponse   *message);
size_t file__upload_response__pack
                     (const File__UploadResponse   *message,
                      uint8_t             *out);
size_t file__upload_response__pack_to_buffer
                     (const File__UploadResponse   *message,
                      ProtobufCBuffer     *buffer);
File__UploadResponse *
       file__upload_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__upload_response__free_unpacked
                     (File__UploadResponse *message,
                      ProtobufCAllocator *allocator);
/* File__DownloadRequest methods */
void   file__download_request__init
                     (File__DownloadRequest         *message);
size_t file__download_request__get_packed_size
                     (const File__DownloadRequest   *message);
size_t file__download_request__pack
                     (const File__DownloadRequest   *message,
                      uint8_t             *out);
size_t file__download_request__pack_to_buffer
                     (const File__DownloadRequest   *message,
                      ProtobufCBuffer     *buffer);
File__DownloadRequest *
       file__download_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__download_request__free_unpacked
                     (File__DownloadRequest *message,
                      ProtobufCAllocator *allocator);
/* File__DownloadResponse methods */
void   file__download_response__init
                     (File__DownloadResponse         *message);
size_t file__download_response__get_packed_size
                     (const File__DownloadResponse   *message);
size_t file__download_response__pack
                     (const File__DownloadResponse   *message,
                      uint8_t             *out);
size_t file__download_response__pack_to_buffer
                     (const File__DownloadResponse   *message,
                      ProtobufCBuffer     *buffer);
File__DownloadResponse *
       file__download_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__download_response__free_unpacked
                     (File__DownloadResponse *message,
                      ProtobufCAllocator *allocator);
/* File__DeleteRequest methods */
void   file__delete_request__init
                     (File__DeleteRequest         *message);
size_t file__delete_request__get_packed_size
                     (const File__DeleteRequest   *message);
size_t file__delete_request__pack
                     (const File__DeleteRequest   *message,
                      uint8_t             *out);
size_t file__delete_request__pack_to_buffer
                     (const File__DeleteRequest   *message,
                      ProtobufCBuffer     *buffer);
File__DeleteRequest *
       file__delete_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__delete_request__free_unpacked
                     (File__DeleteRequest *message,
                      ProtobufCAllocator *allocator);
/* File__DeleteResponse methods */
void   file__delete_response__init
                     (File__DeleteResponse         *message);
size_t file__delete_response__get_packed_size
                     (const File__DeleteResponse   *message);
size_t file__delete_response__pack
                     (const File__DeleteResponse   *message,
                      uint8_t             *out);
size_t file__delete_response__pack_to_buffer
                     (const File__DeleteResponse   *message,
                      ProtobufCBuffer     *buffer);
File__DeleteResponse *
       file__delete_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__delete_response__free_unpacked
                     (File__DeleteResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*File__UploadRequest_Closure)
                 (const File__UploadRequest *message,
                  void *closure_data);
typedef void (*File__FileMetadata_Closure)
                 (const File__FileMetadata *message,
                  void *closure_data);
typedef void (*File__UploadResponse_Closure)
                 (const File__UploadResponse *message,
                  void *closure_data);
typedef void (*File__DownloadRequest_Closure)
                 (const File__DownloadRequest *message,
                  void *closure_data);
typedef void (*File__DownloadResponse_Closure)
                 (const File__DownloadResponse *message,
                  void *closure_data);
typedef void (*File__DeleteRequest_Closure)
                 (const File__DeleteRequest *message,
                  void *closure_data);
typedef void (*File__DeleteResponse_Closure)
                 (const File__DeleteResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct File__FileService_Service File__FileService_Service;
struct File__FileService_Service
{
  ProtobufCService base;
  void (*upload)(File__FileService_Service *service,
                 const File__UploadRequest *input,
                 File__UploadResponse_Closure closure,
                 void *closure_data);
  void (*download)(File__FileService_Service *service,
                   const File__DownloadRequest *input,
                   File__DownloadResponse_Closure closure,
                   void *closure_data);
  void (*delete)(File__FileService_Service *service,
                 const File__DeleteRequest *input,
                 File__DeleteResponse_Closure closure,
                 void *closure_data);
};
typedef void (*File__FileService_ServiceDestroy)(File__FileService_Service *);
void file__file_service__init (File__FileService_Service *service,
                               File__FileService_ServiceDestroy destroy);
#define FILE__FILE_SERVICE__BASE_INIT \
    { &file__file_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define FILE__FILE_SERVICE__INIT(function_prefix__) \
    { FILE__FILE_SERVICE__BASE_INIT,\
      function_prefix__ ## upload,\
      function_prefix__ ## download,\
      function_prefix__ ## delete  }
void file__file_service__upload(ProtobufCService *service,
                                const File__UploadRequest *input,
                                File__UploadResponse_Closure closure,
                                void *closure_data);
void file__file_service__download(ProtobufCService *service,
                                  const File__DownloadRequest *input,
                                  File__DownloadResponse_Closure closure,
                                  void *closure_data);
void file__file_service__delete(ProtobufCService *service,
                                const File__DeleteRequest *input,
                                File__DeleteResponse_Closure closure,
                                void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor file__upload_request__descriptor;
extern const ProtobufCMessageDescriptor file__file_metadata__descriptor;
extern const ProtobufCMessageDescriptor file__upload_response__descriptor;
extern const ProtobufCMessageDescriptor file__download_request__descriptor;
extern const ProtobufCMessageDescriptor file__download_response__descriptor;
extern const ProtobufCMessageDescriptor file__delete_request__descriptor;
extern const ProtobufCMessageDescriptor file__delete_response__descriptor;
extern const ProtobufCServiceDescriptor file__file_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_file_2ffile_2eproto__INCLUDED */
