/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: file/file.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "file/file.pb-c.h"
void   file__upload_request__init
                     (File__UploadRequest         *message)
{
  static const File__UploadRequest init_value = FILE__UPLOAD_REQUEST__INIT;
  *message = init_value;
}
size_t file__upload_request__get_packed_size
                     (const File__UploadRequest *message)
{
  assert(message->base.descriptor == &file__upload_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file__upload_request__pack
                     (const File__UploadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file__upload_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file__upload_request__pack_to_buffer
                     (const File__UploadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file__upload_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
File__UploadRequest *
       file__upload_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (File__UploadRequest *)
     protobuf_c_message_unpack (&file__upload_request__descriptor,
                                allocator, len, data);
}
void   file__upload_request__free_unpacked
                     (File__UploadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file__upload_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file__file_metadata__init
                     (File__FileMetadata         *message)
{
  static const File__FileMetadata init_value = FILE__FILE_METADATA__INIT;
  *message = init_value;
}
size_t file__file_metadata__get_packed_size
                     (const File__FileMetadata *message)
{
  assert(message->base.descriptor == &file__file_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file__file_metadata__pack
                     (const File__FileMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file__file_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file__file_metadata__pack_to_buffer
                     (const File__FileMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file__file_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
File__FileMetadata *
       file__file_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (File__FileMetadata *)
     protobuf_c_message_unpack (&file__file_metadata__descriptor,
                                allocator, len, data);
}
void   file__file_metadata__free_unpacked
                     (File__FileMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file__file_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file__upload_response__init
                     (File__UploadResponse         *message)
{
  static const File__UploadResponse init_value = FILE__UPLOAD_RESPONSE__INIT;
  *message = init_value;
}
size_t file__upload_response__get_packed_size
                     (const File__UploadResponse *message)
{
  assert(message->base.descriptor == &file__upload_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file__upload_response__pack
                     (const File__UploadResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file__upload_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file__upload_response__pack_to_buffer
                     (const File__UploadResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file__upload_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
File__UploadResponse *
       file__upload_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (File__UploadResponse *)
     protobuf_c_message_unpack (&file__upload_response__descriptor,
                                allocator, len, data);
}
void   file__upload_response__free_unpacked
                     (File__UploadResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file__upload_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file__download_request__init
                     (File__DownloadRequest         *message)
{
  static const File__DownloadRequest init_value = FILE__DOWNLOAD_REQUEST__INIT;
  *message = init_value;
}
size_t file__download_request__get_packed_size
                     (const File__DownloadRequest *message)
{
  assert(message->base.descriptor == &file__download_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file__download_request__pack
                     (const File__DownloadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file__download_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file__download_request__pack_to_buffer
                     (const File__DownloadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file__download_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
File__DownloadRequest *
       file__download_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (File__DownloadRequest *)
     protobuf_c_message_unpack (&file__download_request__descriptor,
                                allocator, len, data);
}
void   file__download_request__free_unpacked
                     (File__DownloadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file__download_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file__download_response__init
                     (File__DownloadResponse         *message)
{
  static const File__DownloadResponse init_value = FILE__DOWNLOAD_RESPONSE__INIT;
  *message = init_value;
}
size_t file__download_response__get_packed_size
                     (const File__DownloadResponse *message)
{
  assert(message->base.descriptor == &file__download_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file__download_response__pack
                     (const File__DownloadResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file__download_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file__download_response__pack_to_buffer
                     (const File__DownloadResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file__download_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
File__DownloadResponse *
       file__download_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (File__DownloadResponse *)
     protobuf_c_message_unpack (&file__download_response__descriptor,
                                allocator, len, data);
}
void   file__download_response__free_unpacked
                     (File__DownloadResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file__download_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file__delete_request__init
                     (File__DeleteRequest         *message)
{
  static const File__DeleteRequest init_value = FILE__DELETE_REQUEST__INIT;
  *message = init_value;
}
size_t file__delete_request__get_packed_size
                     (const File__DeleteRequest *message)
{
  assert(message->base.descriptor == &file__delete_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file__delete_request__pack
                     (const File__DeleteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file__delete_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file__delete_request__pack_to_buffer
                     (const File__DeleteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file__delete_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
File__DeleteRequest *
       file__delete_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (File__DeleteRequest *)
     protobuf_c_message_unpack (&file__delete_request__descriptor,
                                allocator, len, data);
}
void   file__delete_request__free_unpacked
                     (File__DeleteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file__delete_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file__delete_response__init
                     (File__DeleteResponse         *message)
{
  static const File__DeleteResponse init_value = FILE__DELETE_RESPONSE__INIT;
  *message = init_value;
}
size_t file__delete_response__get_packed_size
                     (const File__DeleteResponse *message)
{
  assert(message->base.descriptor == &file__delete_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file__delete_response__pack
                     (const File__DeleteResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file__delete_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file__delete_response__pack_to_buffer
                     (const File__DeleteResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file__delete_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
File__DeleteResponse *
       file__delete_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (File__DeleteResponse *)
     protobuf_c_message_unpack (&file__delete_response__descriptor,
                                allocator, len, data);
}
void   file__delete_response__free_unpacked
                     (File__DeleteResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file__delete_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor file__upload_request__field_descriptors[2] =
{
  {
    "metadata",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(File__UploadRequest, data_case),
    offsetof(File__UploadRequest, metadata),
    &file__file_metadata__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunk",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(File__UploadRequest, data_case),
    offsetof(File__UploadRequest, chunk),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file__upload_request__field_indices_by_name[] = {
  1,   /* field[1] = chunk */
  0,   /* field[0] = metadata */
};
static const ProtobufCIntRange file__upload_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor file__upload_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "file.UploadRequest",
  "UploadRequest",
  "File__UploadRequest",
  "file",
  sizeof(File__UploadRequest),
  2,
  file__upload_request__field_descriptors,
  file__upload_request__field_indices_by_name,
  1,  file__upload_request__number_ranges,
  (ProtobufCMessageInit) file__upload_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file__file_metadata__field_descriptors[5] =
{
  {
    "filename",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(File__FileMetadata, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(File__FileMetadata, title),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "artist",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(File__FileMetadata, artist),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "album",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(File__FileMetadata, album),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(File__FileMetadata, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file__file_metadata__field_indices_by_name[] = {
  3,   /* field[3] = album */
  2,   /* field[2] = artist */
  4,   /* field[4] = duration */
  0,   /* field[0] = filename */
  1,   /* field[1] = title */
};
static const ProtobufCIntRange file__file_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor file__file_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "file.FileMetadata",
  "FileMetadata",
  "File__FileMetadata",
  "file",
  sizeof(File__FileMetadata),
  5,
  file__file_metadata__field_descriptors,
  file__file_metadata__field_indices_by_name,
  1,  file__file_metadata__number_ranges,
  (ProtobufCMessageInit) file__file_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file__upload_response__field_descriptors[1] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(File__UploadResponse, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file__upload_response__field_indices_by_name[] = {
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange file__upload_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor file__upload_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "file.UploadResponse",
  "UploadResponse",
  "File__UploadResponse",
  "file",
  sizeof(File__UploadResponse),
  1,
  file__upload_response__field_descriptors,
  file__upload_response__field_indices_by_name,
  1,  file__upload_response__number_ranges,
  (ProtobufCMessageInit) file__upload_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file__download_request__field_descriptors[1] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(File__DownloadRequest, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file__download_request__field_indices_by_name[] = {
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange file__download_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor file__download_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "file.DownloadRequest",
  "DownloadRequest",
  "File__DownloadRequest",
  "file",
  sizeof(File__DownloadRequest),
  1,
  file__download_request__field_descriptors,
  file__download_request__field_indices_by_name,
  1,  file__download_request__number_ranges,
  (ProtobufCMessageInit) file__download_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file__download_response__field_descriptors[1] =
{
  {
    "chunk",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(File__DownloadResponse, chunk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file__download_response__field_indices_by_name[] = {
  0,   /* field[0] = chunk */
};
static const ProtobufCIntRange file__download_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor file__download_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "file.DownloadResponse",
  "DownloadResponse",
  "File__DownloadResponse",
  "file",
  sizeof(File__DownloadResponse),
  1,
  file__download_response__field_descriptors,
  file__download_response__field_indices_by_name,
  1,  file__download_response__number_ranges,
  (ProtobufCMessageInit) file__download_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file__delete_request__field_descriptors[1] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(File__DeleteRequest, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file__delete_request__field_indices_by_name[] = {
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange file__delete_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor file__delete_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "file.DeleteRequest",
  "DeleteRequest",
  "File__DeleteRequest",
  "file",
  sizeof(File__DeleteRequest),
  1,
  file__delete_request__field_descriptors,
  file__delete_request__field_indices_by_name,
  1,  file__delete_request__number_ranges,
  (ProtobufCMessageInit) file__delete_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file__delete_response__field_descriptors[1] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(File__DeleteResponse, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file__delete_response__field_indices_by_name[] = {
  0,   /* field[0] = success */
};
static const ProtobufCIntRange file__delete_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor file__delete_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "file.DeleteResponse",
  "DeleteResponse",
  "File__DeleteResponse",
  "file",
  sizeof(File__DeleteResponse),
  1,
  file__delete_response__field_descriptors,
  file__delete_response__field_indices_by_name,
  1,  file__delete_response__number_ranges,
  (ProtobufCMessageInit) file__delete_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor file__file_service__method_descriptors[3] =
{
  { "Upload", &file__upload_request__descriptor, &file__upload_response__descriptor },
  { "Download", &file__download_request__descriptor, &file__download_response__descriptor },
  { "Delete", &file__delete_request__descriptor, &file__delete_response__descriptor },
};
const unsigned file__file_service__method_indices_by_name[] = {
  2,        /* Delete */
  1,        /* Download */
  0         /* Upload */
};
const ProtobufCServiceDescriptor file__file_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "file.FileService",
  "FileService",
  "File__FileService",
  "file",
  3,
  file__file_service__method_descriptors,
  file__file_service__method_indices_by_name
};
void file__file_service__upload(ProtobufCService *service,
                                const File__UploadRequest *input,
                                File__UploadResponse_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &file__file_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void file__file_service__download(ProtobufCService *service,
                                  const File__DownloadRequest *input,
                                  File__DownloadResponse_Closure closure,
                                  void *closure_data)
{
  assert(service->descriptor == &file__file_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void file__file_service__delete(ProtobufCService *service,
                                const File__DeleteRequest *input,
                                File__DeleteResponse_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &file__file_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void file__file_service__init (File__FileService_Service *service,
                               File__FileService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &file__file_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
