/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auth/auth.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "auth/auth.pb-c.h"
void   auth__register_request__init
                     (Auth__RegisterRequest         *message)
{
  static const Auth__RegisterRequest init_value = AUTH__REGISTER_REQUEST__INIT;
  *message = init_value;
}
size_t auth__register_request__get_packed_size
                     (const Auth__RegisterRequest *message)
{
  assert(message->base.descriptor == &auth__register_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth__register_request__pack
                     (const Auth__RegisterRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth__register_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth__register_request__pack_to_buffer
                     (const Auth__RegisterRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth__register_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Auth__RegisterRequest *
       auth__register_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Auth__RegisterRequest *)
     protobuf_c_message_unpack (&auth__register_request__descriptor,
                                allocator, len, data);
}
void   auth__register_request__free_unpacked
                     (Auth__RegisterRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth__register_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   auth__register_response__init
                     (Auth__RegisterResponse         *message)
{
  static const Auth__RegisterResponse init_value = AUTH__REGISTER_RESPONSE__INIT;
  *message = init_value;
}
size_t auth__register_response__get_packed_size
                     (const Auth__RegisterResponse *message)
{
  assert(message->base.descriptor == &auth__register_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth__register_response__pack
                     (const Auth__RegisterResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth__register_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth__register_response__pack_to_buffer
                     (const Auth__RegisterResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth__register_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Auth__RegisterResponse *
       auth__register_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Auth__RegisterResponse *)
     protobuf_c_message_unpack (&auth__register_response__descriptor,
                                allocator, len, data);
}
void   auth__register_response__free_unpacked
                     (Auth__RegisterResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth__register_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   auth__login_request__init
                     (Auth__LoginRequest         *message)
{
  static const Auth__LoginRequest init_value = AUTH__LOGIN_REQUEST__INIT;
  *message = init_value;
}
size_t auth__login_request__get_packed_size
                     (const Auth__LoginRequest *message)
{
  assert(message->base.descriptor == &auth__login_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth__login_request__pack
                     (const Auth__LoginRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth__login_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth__login_request__pack_to_buffer
                     (const Auth__LoginRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth__login_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Auth__LoginRequest *
       auth__login_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Auth__LoginRequest *)
     protobuf_c_message_unpack (&auth__login_request__descriptor,
                                allocator, len, data);
}
void   auth__login_request__free_unpacked
                     (Auth__LoginRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth__login_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   auth__login_response__init
                     (Auth__LoginResponse         *message)
{
  static const Auth__LoginResponse init_value = AUTH__LOGIN_RESPONSE__INIT;
  *message = init_value;
}
size_t auth__login_response__get_packed_size
                     (const Auth__LoginResponse *message)
{
  assert(message->base.descriptor == &auth__login_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth__login_response__pack
                     (const Auth__LoginResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth__login_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth__login_response__pack_to_buffer
                     (const Auth__LoginResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth__login_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Auth__LoginResponse *
       auth__login_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Auth__LoginResponse *)
     protobuf_c_message_unpack (&auth__login_response__descriptor,
                                allocator, len, data);
}
void   auth__login_response__free_unpacked
                     (Auth__LoginResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth__login_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor auth__register_request__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Auth__RegisterRequest, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Auth__RegisterRequest, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "security_key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Auth__RegisterRequest, security_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth__register_request__field_indices_by_name[] = {
  1,   /* field[1] = password */
  2,   /* field[2] = security_key */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange auth__register_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor auth__register_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "auth.RegisterRequest",
  "RegisterRequest",
  "Auth__RegisterRequest",
  "auth",
  sizeof(Auth__RegisterRequest),
  3,
  auth__register_request__field_descriptors,
  auth__register_request__field_indices_by_name,
  1,  auth__register_request__number_ranges,
  (ProtobufCMessageInit) auth__register_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor auth__register_response__field_descriptors[1] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Auth__RegisterResponse, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth__register_response__field_indices_by_name[] = {
  0,   /* field[0] = token */
};
static const ProtobufCIntRange auth__register_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor auth__register_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "auth.RegisterResponse",
  "RegisterResponse",
  "Auth__RegisterResponse",
  "auth",
  sizeof(Auth__RegisterResponse),
  1,
  auth__register_response__field_descriptors,
  auth__register_response__field_indices_by_name,
  1,  auth__register_response__number_ranges,
  (ProtobufCMessageInit) auth__register_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor auth__login_request__field_descriptors[2] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Auth__LoginRequest, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Auth__LoginRequest, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth__login_request__field_indices_by_name[] = {
  1,   /* field[1] = password */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange auth__login_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor auth__login_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "auth.LoginRequest",
  "LoginRequest",
  "Auth__LoginRequest",
  "auth",
  sizeof(Auth__LoginRequest),
  2,
  auth__login_request__field_descriptors,
  auth__login_request__field_indices_by_name,
  1,  auth__login_request__number_ranges,
  (ProtobufCMessageInit) auth__login_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor auth__login_response__field_descriptors[1] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Auth__LoginResponse, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth__login_response__field_indices_by_name[] = {
  0,   /* field[0] = token */
};
static const ProtobufCIntRange auth__login_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor auth__login_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "auth.LoginResponse",
  "LoginResponse",
  "Auth__LoginResponse",
  "auth",
  sizeof(Auth__LoginResponse),
  1,
  auth__login_response__field_descriptors,
  auth__login_response__field_indices_by_name,
  1,  auth__login_response__number_ranges,
  (ProtobufCMessageInit) auth__login_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor auth__auth_service__method_descriptors[2] =
{
  { "Register", &auth__register_request__descriptor, &auth__register_response__descriptor },
  { "Login", &auth__login_request__descriptor, &auth__login_response__descriptor },
};
const unsigned auth__auth_service__method_indices_by_name[] = {
  1,        /* Login */
  0         /* Register */
};
const ProtobufCServiceDescriptor auth__auth_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "auth.AuthService",
  "AuthService",
  "Auth__AuthService",
  "auth",
  2,
  auth__auth_service__method_descriptors,
  auth__auth_service__method_indices_by_name
};
void auth__auth_service__register(ProtobufCService *service,
                                  const Auth__RegisterRequest *input,
                                  Auth__RegisterResponse_Closure closure,
                                  void *closure_data)
{
  assert(service->descriptor == &auth__auth_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void auth__auth_service__login(ProtobufCService *service,
                               const Auth__LoginRequest *input,
                               Auth__LoginResponse_Closure closure,
                               void *closure_data)
{
  assert(service->descriptor == &auth__auth_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void auth__auth_service__init (Auth__AuthService_Service *service,
                               Auth__AuthService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &auth__auth_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
